name : CI

on :
  push:
    paths:
      - 'src/**' 
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: 
        python-version: ["3.9"]

  steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

     - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}


