swagger: "2.0"
info:
  title: league-api
  description: openapi spec file for backend cloud run python analysis tool
  version: 1.0.0
schemes:
- https
x-google-backend:
  address: https://sports-yekomza2pq-nw.a.run.app
security:
  - api_key: []
produces:
  - application/json
consumes:
  - application/json
paths:
  /leagues:
    get:
      summary: returns a JSON string "this works!"
      operationId: getTestMessage
      responses:
        200:
          description: OK
          schema:
            type: string
